FROM openjdk:17-alpine

WORKDIR usr/src

ADD /target/insurance-0.0.1-SNAPSHOT.jar /usr/src/insurance-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","insurance-0.0.1-SNAPSHOT.jar"]

ENV MONGOURL=mongodb://mongos:27017/insuranceProduct