FROM openjdk:17-alpine

WORKDIR usr/src

ADD /target/notificationService-0.0.1-SNAPSHOT.jar /usr/src/notificationService-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","notificationService-0.0.1-SNAPSHOT.jar"]

ENV MONGOURL=mongodb://mongos:27017/insuranceNotification