version: '3.7'

services:

  mongos:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGOURL: mongodb://localhost:27017/insurance

  notification:
    image: paramvir28/notification
    depends_on:
      - mongos
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 9098:9098
