version: '3.7'

services:

  mongos:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGOURL: mongodb://localhost:27017/insurance
      
  product_purchased_service:
    image: longswordfish/product_purchased_service
    depends_on:
      - mongos
    restart: always
    ports:
      - 9094:9094

  eureka_server:
    image: longswordfish/eureka_server
    restart: always
    ports:
      - 8761:8761
  