FROM openjdk:17-alpine

WORKDIR usr/src

ADD /target/Review-0.0.1-SNAPSHOT.jar /usr/src/Review-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","Review-0.0.1-SNAPSHOT.jar"]

ENV MONGOURL=mongodb://mongos:27017/insuranceReview